# This file was generated by GoReleaser. DO NOT EDIT.
cask "dwe" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "bcd15ba24a969c3b85f7e30daa893f576eef8ec06620918a2314721713fbe9bf"
      url "https://github.com/semsemyonoff/dwe/releases/download/v#{version}/dwe_#{version}_macos_arm64.tar.gz"
    end
    on_intel do
      sha256 "3dd979df7eeb13ce45153f9e2565be2737e8b96e0e27eec569e60d2224fe0fc4"
      url "https://github.com/semsemyonoff/dwe/releases/download/v#{version}/dwe_#{version}_macos_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2af1f3c92f6a32ec77fba4954cf3b9bf1ee648c8ed7eaf9b9414a9494e9fd034"
      url "https://github.com/semsemyonoff/dwe/releases/download/v#{version}/dwe_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4bb4b78cd50070eb65987aca3de3f7c833e1f4969e06e4a7406ae5bef404e849"
      url "https://github.com/semsemyonoff/dwe/releases/download/v#{version}/dwe_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "dwe"
  desc "Docker-based developer environment manager"
  homepage "https://github.com/semsemyonoff/dwe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dwe"
  bash_completion "completions/dwe.bash"
  fish_completion "completions/dwe.fish"
  zsh_completion "completions/dwe.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dwe"]
    end
  end

  # No zap stanza required
end
