# This file was generated by GoReleaser. DO NOT EDIT.
cask "dwe" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/dwe"]
    end
  end

  version "0.6.3"

  on_macos do
    on_arm do
      sha256 "b11b36b42608489fa016a4242fdc5be5e78b4ca89122092372f9ea357818491d"
      url "https://github.com/semsemyonoff/dwe/releases/download/v#{version}/dwe_#{version}_macos_arm64.tar.gz"
    end
    on_intel do
      sha256 "32745f30cd563182f3a0942f69a5323fe655a83b4ea7c836901195bf310c51d2"
      url "https://github.com/semsemyonoff/dwe/releases/download/v#{version}/dwe_#{version}_macos_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6f2f03c212b8c8a77b87ce8de5fd31fe1669e69ac609ccc85e226c3c1f147022"
      url "https://github.com/semsemyonoff/dwe/releases/download/v#{version}/dwe_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5f8ec7c08b71446c614562adc0bcca708d38996f4ac7b77b32b5db3485a3722f"
      url "https://github.com/semsemyonoff/dwe/releases/download/v#{version}/dwe_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "dwe"
  desc "Docker-based developer environment manager"
  homepage "https://github.com/semsemyonoff/dwe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dwe"
  bash_completion "completions/dwe.bash"
  fish_completion "completions/dwe.fish"
  zsh_completion "completions/dwe.zsh"

  # No zap stanza required
end
