# This file was generated by GoReleaser. DO NOT EDIT.
cask "dwe" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "09a8df9665c57214ba6b0e2caeae5d3b3186b5efaa9f40393031e261232d8686"
      url "https://github.com/semsemyonoff/dwe/releases/download/v#{version}/dwe_#{version}_macos_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c0a625d476795e832b209ea3a10a22d792a31863fa1c4fafa8844c1afe4212ee"
      url "https://github.com/semsemyonoff/dwe/releases/download/v#{version}/dwe_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6e1acbf0f7da0335752ca1940a85c4a909bcc5c031aa809d9fcd2bdfe4163b1e"
      url "https://github.com/semsemyonoff/dwe/releases/download/v#{version}/dwe_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ace066e0c94018df90b846ec483bb5aca6cd9107c2213ecab0c9255565f06f7f"
      url "https://github.com/semsemyonoff/dwe/releases/download/v#{version}/dwe_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dwe"
  desc "Docker-based developer environment manager"
  homepage "https://github.com/semsemyonoff/dwe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dwe"
  bash_completion "completions/dwe.bash"
  fish_completion "completions/dwe.fish"
  zsh_completion "completions/dwe.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dwe"]
    end
  end

  # No zap stanza required

end
